version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MongoConnectionString=mongodb://mongo:27017
    ports:
      - "5000:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: maanoelaurias
      MONGO_INITDB_ROOT_PASSWORD: senha123
